steps:
  - label: ":hammer: Example Script"
    command: echo "Hello Buildkite !!"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
  
  #- label: ":bulb: Clean Package"
  #  command: "mvn clean"
    
  - label: ":lollipop: Test"
    command: "mvn test"
    key: test-step
    plugins:
      - test-collector#v1.0.0:
          files: "/home/dulanjana_aws/junit-test.xml"
          format: "junit"