steps:
  - label: ":hammer: Example Script"
    command: echo "Hello Buildkite !!"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    
  - label: ":lollipop: Test"
    command: "mvn test"

  #- label: "Upload Files to Test Analytics"
  #  commands:
      #- 'curl -X POST  -H "Authorization: Token token=\$BUILDKITE_ANALYTICS_TOKEN"  -F "format=junit"  -F "data=@junit4-demo/target/surefire-reports/TEST-jcg.zheng.demo.junit4.SomeClassTest.xml"  -F "run_env[CI]=buildkite"  -F "run_env[key]=$BUILDKITE_BUILD_ID"  -F "run_env[number]=$BUILDKITE_BUILD_NUMBER" -F "run_env[job_id]=$BUILDKITE_JOB_ID"  -F "run_env[branch]=$BUILDKITE_BRANCH"  -F "run_env[commit_sha]=$BUILDKITE_COMMIT"  -F "run_env[url]=$BUILDKITE_BUILD_URL" https://analytics-api.buildkite.com/v1/uploads'
      #- 'curl -X POST  -H "Authorization: Token token=\$BUILDKITE_ANALYTICS_TOKEN"  -F "format=junit"  -F "data=@junit5-demo/target/surefire-reports/TEST-jcg.zheng.demo.junit5.SomeClassTest.xml"  -F "run_env[CI]=buildkite"  -F "run_env[key]=$BUILDKITE_BUILD_ID"  -F "run_env[number]=$BUILDKITE_BUILD_NUMBER" -F "run_env[job_id]=$BUILDKITE_JOB_ID"  -F "run_env[branch]=$BUILDKITE_BRANCH"  -F "run_env[commit_sha]=$BUILDKITE_COMMIT"  -F "run_env[url]=$BUILDKITE_BUILD_URL" https://analytics-api.buildkite.com/v1/uploads'
  #  key: test-step
  #  plugins:
  #    - git-clean#v1.0.0:
  #        flags: "quit"
    
